name: build
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21, 25 ]
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          # Being in the last position, the latest JDK is used by default to build, the version from the matrix is made
          # available to run the tests, to check compatibility.
          java-version: |
            ${{ matrix.java-version }}
            25

      - name: Check
        run: ./gradlew assemble check --info
        env:
          TEST_JAVA_TOOLCHAIN: ${{ matrix.java-version }}

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: reports-${{ strategy.job-index }}
          path: build/reports